#!/bin/bash
#
# Create device files

mkdir -v _install/dev

mknod -m 600 _install/dev/console c 5 1
mknod -m 666 _install/dev/full c 1 7
mknod -m 666 _install/dev/kmem c 1 2
mknod -m 666 _install/dev/mem c 1 1
mknod -m 666 _install/dev/null c 1 3
mknod -m 666 _install/dev/port c 1 4
mknod -m 444 _install/dev/random c 1 8
mknod -m 444 _install/dev/urandom c 1 9
mknod -m 666 _install/dev/zero c 1 5
mknod -m 666 _install/dev/ram0 b 1 0

#Only create two hard drive devs, more can be added
mknod -m 644 _install/dev/hda b 3 0
mknod -m 644 _install/dev/hdb b 3 64

mknod -m 644 _install/dev/tty c 5 0
mknod -m 644 _install/dev/tty0 c 4 0
mknod -m 644 _install/dev/tty1 c 4 1 
mknod -m 644 _install/dev/tty2 c 4 2
mknod -m 644 _install/dev/tty3 c 4 3
mknod -m 644 _install/dev/tty4 c 4 4
mknod -m 644 _install/dev/tty5 c 4 5
mknod -m 644 _install/dev/vcs0 b 7 0

cp -avp /dev/core   _install/dev
cp -avp /dev/stderr   _install/dev
cp -avp /dev/stdin   _install/dev
cp -avp /dev/stdout   _install/dev

mkdir -v _install/dev/shm
