#!/bin/bash
#
# Create device files

mknod -m 600 dev/console c 5 1
mknod -m 666 dev/full c 1 7
mknod -m 666 dev/kmem c 1 2
mknod -m 666 dev/mem c 1 1
mknod -m 666 dev/null c 1 3
mknod -m 666 dev/port c 1 4
mknod -m 444 dev/random c 1 8
mknod -m 444 dev/urandom c 1 9
mknod -m 666 dev/zero c 1 5
mknod -m 666 dev/ram0 b 1 0

#Only create two hard drive devs, more can be added
mknod -m 644 dev/hda b 3 0
mknod -m 644 dev/hdb b 3 64

mknod -m 644 dev/tty c 5 0
mknod -m 644 dev/tty0 c 4 0
mknod -m 644 dev/tty1 c 4 1 
mknod -m 644 dev/tty2 c 4 2
mknod -m 644 dev/tty3 c 4 3
mknod -m 644 dev/tty4 c 4 4
mknod -m 644 dev/tty5 c 4 5
mknod -m 644 dev/vcs0 b 7 0

cp -avp /dev/core   dev
cp -avp /dev/stderr   dev
cp -avp /dev/stdin   dev
cp -avp /dev/stdout   dev

mkdir -v dev/shm
